### ISSUE TITLE
.gitkeepがignoreされてない

### ISSUE THREAD

**Issue by nabeen** [Catatsu/Asada_NewProject#2]
@AsadaShumei .gitignoreに入れろぉォォォォォォォォオオオ!!

**Comment by AsadaShumei** [comment]
@nabeen .gitkeepを.hitignoreに入れると、Assetsﾃﾞｨﾚｸﾄﾘがｺﾐｯﾄ対象から外れちゃうので、ﾀﾞﾒな認識なのですが……間違えてます？

**Comment by nabeen** [comment]
うわぁぁぁぁぁぁぁほんまやぁぁぁぁぁぁごめんんんんんんん！
